-- 코드를 입력하세요
WITH rankedRest AS (SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES,
ROW_NUMBER() OVER (PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS rnk
FROM REST_INFO)

SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM rankedRest
WHERE rnk = 1 
ORDER BY FOOD_TYPE DESC

