-- 코드를 입력하세요
# WITH USERS AS (SELECT USER_ID, YEAR(JOINED) AS YEAR, MONTH(JOINED) AS MONTH
# FROM USER_INFO
# WHERE JOINED LIKE '2021%'
# GROUP BY USER_ID)

SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH,

COUNT(DISTINCT ONLINE_SALE.USER_ID) AS PURCHASED_USERS,
ROUND(COUNT(DISTINCT ONLINE_SALE.USER_ID) / 
      (SELECT COUNT(*) FROM USER_INFO WHERE JOINED LIKE '2021%'), 1) AS PUCHASED_RATIO


FROM USER_INFO 
JOIN ONLINE_SALE ON USER_INFO.USER_ID = ONLINE_SALE.USER_ID
WHERE JOINED LIKE '2021%'
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH


