WITH FRONT_END AS (SELECT SUM(CODE)
                  FROM SKILLCODES
                  WHERE CATEGORY = "Front End")

SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS
WHERE SKILL_CODE & (SELECT * FROM FRONT_END)
ORDER BY ID