-- 코드를 작성해주세요
WITH SCORE_AVG AS (
SELECT EMP_NO, AVG(SCORE) AS S_AVG
FROM HR_GRADE
GROUP BY EMP_NO
) 

SELECT HR_EMPLOYEES.EMP_NO, EMP_NAME, 
CASE WHEN S_AVG >= 96 THEN 'S'
WHEN S_AVG >= 90 THEN 'A'
WHEN S_AVG >= 80 THEN 'B'
ELSE 'C' END GRADE,

CASE WHEN S_AVG >= 96 THEN SAL * 0.2
WHEN S_AVG >= 90 THEN SAL * 0.15
WHEN S_AVG >= 80 THEN SAL * 0.1
ELSE SAL * 0 END BONUS

FROM SCORE_AVG
JOIN HR_EMPLOYEES ON SCORE_AVG.EMP_NO = HR_EMPLOYEES.EMP_NO