SELECT P.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE P
JOIN REST_REVIEW R ON P.MEMBER_ID = R.MEMBER_ID

where P.MEMBER_ID = (select MEMBER_ID from REST_REVIEW group by MEMBER_ID
                    order by count(*) DESC limit 1
                    )

ORDER BY REVIEW_DATE, R.REVIEW_TEXT