SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE DATE_FORMAT(START_DATE, '%Y-%m') BETWEEN '2022-08' AND '2022-10'
AND CAR_ID IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
              where date_format(START_DATE, '%Y-%m') BETWEEN '2022-08' AND '2022-10'
               group by car_id
               having count(car_id) >= 5
              )
GROUP BY MONTH, CAR_ID
ORDER BY MONTH, CAR_ID DESC