SELECT PRODUCT_CODE,
  CASE 
    WHEN LENGTH(REGEXP_REPLACE(PRODUCT_CODE, '[^0-9]', '')) <= 4 THEN LPAD(REGEXP_REPLACE(PRODUCT_CODE, '[^0-9]', ''), 4, '0') 
    ELSE REGEXP_REPLACE(PRODUCT_CODE, '[^0-9]', '') 
  END AS PRODUCT_CODE	
FROM PRODUCT